### ISSUE TITLE
Show mosque id in mobile app

### ISSUE THREAD

**Issue by thehungrycoder** [prayersconnect/Prayers-Connect#1]
- Show mosque id number so people can easily refer it to. 
- ~Add a new action item on mosque detail page to email which opens email client with recipient and subject line auto filled with mosque identifying info (like id)~ Done

**Comment by prayersconnect** [comment]
Added mosque id on mosque details page. 
<img width="330" alt="Screen Shot 2020-04-11 at 5 43 12 PM" src="https://user-images.githubusercontent.com/55450646/79055556-ef5c8280-7c1b-11ea-9a59-50400a9e094c.png">
