### ISSUE TITLE
Regression tests

### ISSUE THREAD

**Issue by prayersconnect** [prayersconnect/Prayers-Connect#11]
Tests following aspects before releasing 2.4.0
- No react deprecation alerts
- Sync iqamah times (FavoriteMosqueSyncHandler)
- AutoMosqueFavorite handler 
- DeviceTokenSyncer  handler 
- AppURLScheme handler

**Comment by thehungrycoder** [comment]
Verified everything. Ma be AppURLScheme handler still broken but we've already released this in 2.4.5
