### ISSUE TITLE
Improve search on map

### ISSUE THREAD

**Issue by thehungrycoder** [prayersconnect/Prayers-Connect#3]
Currently, the search on map has a few limitation. It returns N closest mosques. So if in one side, there are many/enough (of N) number of mosques, other side won't show any mosques. Like, if visible area is manhattan and bronx, most of the mosques will be shown in manhattan (assuming moving map from manhattan area to bronx area) as current N value (20) is already met.

Rather, it should
- Get bounding box (current visible area). PR is in progress https://github.com/react-community/react-native-maps/pull/2571
- Add a new endpoint that takes bounding box as parameter and returns ALL mosques in that box. Geocoder already supports it out of the box https://github.com/alexreisner/geocoder#advanced-database-queries

**Comment by prayersconnect** [comment]
this is done.
